### PR TITLE
Don't pin sphinx to a specific version just for a theme file

### PR DESCRIPTION
**Pull request by fiendish**

### CODE REVIEW

**Comment by dankolbman** [comment]
What issue does this solve?

**Comment by fiendish** [comment]
version conflict from something else needing a different version

**Comment by fiendish** [comment]
Sphinx 1.8.1 has broken implementation for csv-table import file paths. Can we merge this? A theme file shouldn't be able to mandate the software version.

**Comment by fiendish** [comment]
Circle appears to now be broken on this repository. Build failure is unrelated to this PR.

**Review by dankolbman — DISMISSED** [review]
# 🔥

**Review by dankolbman — APPROVED** [review]
# ⛲️

**Pull request merged**
